version: '3.1'
services:
  postgreDB:
    image: postgres
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres-db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-clave
      - POSTGRES_USER_FILE=/run/secrets/postgres-usuario
    secrets:
      - postgres-db
      - postgres-usuario
      - postgres-clave
    volumes:
      - volumen-postgres:/var/lib/postgresql/data
      - ./script-bdprueba.sql:/docker-entrypoint-initdb.d/1-init.sql
  codespaces:
    image: codercom/code-server
    tty: true
    ports:
      - "81:8080"
    volumes:
      - ./app:/app:rw
      - ./config:/home/coder/.config/code-server
  node_backend:
     image: sgssiworks/node_simpleapp_backend
     ports:
       - "80:8080"
     #volumes:
       #- ./app/web/back:/usr/app
     #command: nodemon server.js

volumes:
  volumen-postgres:

secrets:
  postgres-db:
    file: postgres-db.txt
  postgres-usuario:
    file: postgres-usuario.txt
  postgres-clave:
    file: postgres-clave.txt
