version: '3.1'
services:
  postgreDB:
    image: postgres
    environment:
      - POSTGRES_DB=db_pruebas
      - POSTGRES_PASSWORD=abc123.
      - POSTGRES_USER=eufrasio
    volumes:
      - volumen-postgres:/var/lib/postgresql/data
      - ./script-bdprueba.sql:/docker-entrypoint-initdb.d/1-init.sql
  codespaces:
    image: codercom/code-server
    tty: true
    ports:
      - "80:8080"
    volumes:
      - ./app:/app:rw
      - ./config:/home/coder/.config/code-server
  node_backend:
     image: sgssiworks/node_simpleapp_backend
     ports:
       - "81:8080"
     #volumes:
       #- ./app/web/back:/usr/app
     command: nodemon server.js

volumes:
  volumen-postgres:
