apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-carga-datos
data:
  initdb.sql: |
    CREATE TABLE visitas (id SERIAL, nombre VARCHAR(45), texto VARCHAR(45), PRIMARY KEY(id));
    INSERT INTO visitas (nombre, texto) VALUES ('Unai', 'Probando entrada desde K8S');
    